from cmp import db

class AliyunVm(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    InstanceId = db.Column(db.String(50))
    InstanceName = db.Column(db.String(50))
    ZoneId = db.Column(db.String(50))
    RegionId = db.Column(db.String(50))
    AccountName = db.Column(db.String(50))
    InstanceType = db.Column(db.String(50))
    PrivateIp = db.Column(db.String(50))
    PublicIP = db.Column(db.String(50))
    Memory = db.Column(db.String(50))
    Cpu = db.Column(db.String(50))
    OSName = db.Column(db.String(50))
    CreationTime = db.Column(db.String(50))
    MonthPrice = db.Column(db.String(50))
    dnats = db.relationship('AliyunDnat')

class AliyunDnat(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    ExternalPort = db.Column(db.String(10))
    ExternalIp = db.Column(db.String(20))
    InternalPort = db.Column(db.String(10))
    InternalIp = db.Column(db.String(20))
    vm_id = db.Column(db.Integer, db.ForeignKey('aliyun_vm.id'))

class AliyunRds(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    DBInstanceId = db.Column(db.String(50))
    ConnectionString = db.Column(db.String(100))
    AccountName = db.Column(db.String(50))
    ZoneId = db.Column(db.String(50))
    RegionId = db.Column(db.String(50))
    Port = db.Column(db.String(10))
    DBInstanceDescription = db.Column(db.String(50))
    DBInstanceClass = db.Column(db.String(50))
    DBInstanceCPU = db.Column(db.String(10))
    DBInstanceMemory = db.Column(db.String(10))
    DBInstanceStorage = db.Column(db.String(50))
    CreationTime = db.Column(db.String(50))
    ExpireTime = db.Column(db.String(50))
    Engine = db.Column(db.String(50))
    SecurityIPList = db.Column(db.String(100))
    MonthPrice = db.Column(db.String(50))

class AliyunCdn(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    DomainName = db.Column(db.String(50))
    Cname = db.Column(db.String(50))
    CreationTime = db.Column(db.String(50))
    Coverage = db.Column(db.String(20))
    OriginAddress = db.Column(db.String(50))

class AliyunWaf(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    DomainName = db.Column(db.String(50))
    OriginAddress = db.Column(db.String(50))
    HttpPort = db.Column(db.String(10))
    HttpsPort = db.Column(db.String(10))
    Cname = db.Column(db.String(50))
    AccountName = db.Column(db.String(20))

class AliyunSsl(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    CertName = db.Column(db.String(50))
    CertId = db.Column(db.String(50))
    DomainName = db.Column(db.String(200))
    Issuer = db.Column(db.String(50))
    StartDate = db.Column(db.String(50))
    EndDate = db.Column(db.String(50))
    AccountName = db.Column(db.String(50))

class AliyunOss(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    BucketName = db.Column(db.String(50))
    VolThisMon = db.Column(db.String(50))
    VolLastMon = db.Column(db.String(50))
    ReqThisMon = db.Column(db.String(50))
    ReqLastMon = db.Column(db.String(50))
    RecvThisMon = db.Column(db.String(50))
    RecvLastMon = db.Column(db.String(50))
    SendThisMon = db.Column(db.String(50))
    SendLastMon = db.Column(db.String(50))

class OcVm(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    Name = db.Column(db.String(50))
    PrivateIp = db.Column(db.String(50))
    PublicIp = db.Column(db.String(50))
    Zone = db.Column(db.String(50))
    State = db.Column(db.String(50))
    Shape = db.Column(db.String(50))
    NumOfCpu = db.Column(db.String(50))
    CpuDesc = db.Column(db.String(50))
    Memory = db.Column(db.String(50))
    Bandwidth = db.Column(db.String(50))
    CreatedOn = db.Column(db.String(50))
   
class AzVm(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    Name = db.Column(db.String(50))
    PrivateIp = db.Column(db.String(50))
    PublicIp = db.Column(db.String(50))
    HardwareProfile = db.Column(db.String(50))
    ResourceGroup = db.Column(db.String(50))
    Location = db.Column(db.String(50))
    OsDiskSizeGb = db.Column(db.String(50))
    DataDiskSizeGb = db.Column(db.String(50))
    Image = db.Column(db.String(50))

class AzDb(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    Name = db.Column(db.String(50))
    CreationDate = db.Column(db.String(50))
    ResourceGroup = db.Column(db.String(50))
    Location = db.Column(db.String(50))
    UsedBytes = db.Column(db.String(50))
    MaxSizeBytes = db.Column(db.String(50))
    Status = db.Column(db.String(50))
    EarliestRestoreDate = db.Column(db.String(50))
    Type = db.Column(db.String(50))
    Tier = db.Column(db.String(50))
    Collation = db.Column(db.String(50))

class DnsPodDomains(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    DomainId = db.Column(db.String(50))
    DomainName = db.Column(db.String(50))
    CreationTime = db.Column(db.String(50))
    UpdateTime = db.Column(db.String(50))
    Records = db.Column(db.String(50))

class DnsPodRecords(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    ChildDomain = db.Column(db.String(50))
    ParentDomain = db.Column(db.String(50))
    Value = db.Column(db.String(200))
    UpdateTime = db.Column(db.String(50))
    Type = db.Column(db.String(50))
    Enabled = db.Column(db.String(5))
